### ISSUE TITLE
Download from Spaces?

### ISSUE THREAD

**Issue by GitBreezePaul** [marceloavf/digitalocean-tools-vsts#8]
## Feature Request
This is an excellent extension. Is there a reason why there is no 'download' task in it? Did you not need it, or is this problematic with Azure?

I appreciate you're doing this in your spare time. I don't have time to write this task right now, but I may do in the future. I just don't want to work on it if it is already a work in progress.

Thanks!

**Comment by marceloavf** [comment]
Hey @Blightysoft 

First of all thank you, I focused first in upload and delete because our team needed it, but it was done in a way that is possible to expand to new features.

For now I'm not working on it, but you can sure do a PR for this and if I start working on it I'll let you know in this issue.

Thank you again.

**Comment by GitBreezePaul** [comment]
Excellent work. We didn't need it in the end, but that's great to have. Many thanks!
